### ISSUE TITLE
Script not working, giving errors

### ISSUE THREAD

**Issue by Remourz** [faiyazahmad07/WEBSTER#2]
Hello script is not working i'm running : python3 webster.py -u https://evil.com , for testing and it gives this:

       __        __   _         _
       \ \      / /__| |__  ___| |_ ___ _ __
        \ \ /\ / / _ \ '_ \/ __| __/ _ \ '__|
         \ V  V /  __/ |_) \__ \ ||  __/ |
          \_/\_/ \___|_.__/|___/\__\___|_|
             Open Redirection Scanner
                 By: Faiyaz Ahmad
                @bepractical.tech

Traceback (most recent call last):
  File "webster.py", line 137, in <module>
    Scanner(url,payload_file)
  File "webster.py", line 35, in __init__
    payloads = self.payload_parser()
  File "webster.py", line 87, in payload_parser
    total_payload = self.open_file()
  File "webster.py", line 78, in open_file
    with open(self.payload_file,'r') as data:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by faiyazahmad07** [comment]
Hi, You need to specify the payload's path.

Try: python3 webster.py -u https://example.com/?redir=val -p payloads.txt -t 1 -w example.com
